### ISSUE TITLE
Šiauliai -> Šiaulių nekeičia

### ISSUE THREAD

**Issue by beinoriusju** [RokasAniss/vardas#14]
`vardas('Šiauliai').linksnis('kilmininkas')` nekeičia į Šiaulių

Taip pat nekeičia ir šių miestų:

- Druskininkai nekeičia į Druskininkų
- Eišiškės nekeičia į Eišiškių
- Dusetos nekeičia į Dusetų
- Zarasai nekeičia į Zarasų

**Comment by RokasAnisas** [comment]
@beinoriusju Dėkoju už pastabas! Džiaugiuosi, kad kažkas naudoja šią biblioteką. Pataisymai pagal pastabas jau išleisti, gero naudojimo!
